#!/usr/bin/env bash

set -o xtrace

SOURCE="${BASH_SOURCE[0]}"
if [[ -h $SOURCE ]]; then
  SOURCE="$( readlink "$SOURCE" )"
fi

SOURCE_ROOT="${SOURCE_ROOT:-$( cd -P "$( dirname "$SOURCE" )/.." && pwd )}"

clean_review_information() {
  local out="$SOURCE_ROOT/fastlane/metadata/review_information"
  rm "$out/email_address.txt"
  rm "$out/phone_number.txt"
}

clean_trade_representative_contact_information() {
  local out="$SOURCE_ROOT/fastlane/metadata/trade_representative_contact_information"
  rm "$out/address_line1.txt"
  rm "$out/city_name.txt"
  rm "$out/email_address.txt"
  rm "$out/phone_number.txt"
  rm "$out/postal_code.txt"
  rm "$out/trade_name.txt"
}

clean() {
  clean_review_information
  clean_trade_representative_contact_information
}

clean

exit 0
