#!/usr/bin/env bash

set -o xtrace

SOURCE="${BASH_SOURCE[0]}"
if [[ -h $SOURCE ]]; then
  SOURCE="$( readlink "$SOURCE" )"
fi

SOURCE_ROOT="${SOURCE_ROOT:-$( cd -P "$( dirname "$SOURCE" )/.." && pwd )}"

snapfile() {
  local in="$SOURCE_ROOT/fastlane/Snapfile.in"
  local out="$SOURCE_ROOT/fastlane/Snapfile"
  sed \
    -e "s;@@WORKSPACE@@;$WORKSPACE;g" \
    $in > $out
}

review_information() {
  local out="$SOURCE_ROOT/fastlane/metadata/review_information"
  echo "$EMAIL_ADDRESS" > "$out/email_address.txt"
  echo "$PHONE_NUMBER" > "$out/phone_number.txt"
}

trade_representative_contact_information() {
  local out="$SOURCE_ROOT/fastlane/metadata/trade_representative_contact_information"
  echo "$ADDRESS_LINE1" > "$out/address_line1.txt"
  echo "$CITY_NAME" > "$out/city_name.txt"
  echo "$EMAIL_ADDRESS" > "$out/email_address.txt"
  echo "$PHONE_NUMBER" > "$out/phone_number.txt"
  echo "$POSTAL_CODE" > "$out/postal_code.txt"
  echo "$TRADE_NAME" > "$out/trade_name.txt"
}

edit_fastlane() {
  snapfile
  review_information
  trade_representative_contact_information
}

edit_fastlane

exit 0
