#!/usr/bin/env bash

set -o xtrace

SOURCE="${BASH_SOURCE[0]}"
if [[ -h $SOURCE ]]; then
  SOURCE="$( readlink "$SOURCE" )"
fi

SOURCE_ROOT="${SOURCE_ROOT:-$( cd -P "$( dirname "$SOURCE" )/.." && pwd )}"

if [ "$1" == "" ]; then
  echo "Pass domain name to be added to exceptions for receiving full ATS protections"
  exit 1
fi

PLISTBUDDY=/usr/libexec/PlistBuddy
INFO_PLIST="$SOURCE_ROOT/Podest/Info.plist"

$PLISTBUDDY -c "Add :NSAppTransportSecurity:NSExceptionDomains:$1 dict" $INFO_PLIST
