#!/usr/bin/env bash

set -o xtrace

SOURCE="${BASH_SOURCE[0]}"
if [[ -h $SOURCE ]]; then
  SOURCE="$( readlink "$SOURCE" )"
fi

SOURCE_ROOT="${SOURCE_ROOT:-$( cd -P "$( dirname "$SOURCE" )/.." && pwd )}"
PLISTBUDDY=/usr/libexec/PlistBuddy
INFO_PLIST="$SOURCE_ROOT/Podest/Info.plist"
SETTINGS_PLIST="$SOURCE_ROOT/Settings.bundle/Root.plist"

VERSION="$MARKETING_VERSION ($CURRENT_PROJECT_VERSION)"

$PLISTBUDDY -c "Set :PreferenceSpecifiers:5:DefaultValue $VERSION" $SETTINGS_PLIST
